### ISSUE TITLE
Push it to github

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer-fest#2]
cc @tunnckoCore 

http://npm.im/jstransformer-fest

**Comment by tunnckoCore** [comment]
@RobLoach mm yea, they are not ready (that are in my profile). I'll move them when they are rdy.
Sorry for the delay, but I'm busy.

**Comment by RobLoach** [comment]
@tunnckoCore If it's not ready, then push it to GitHub so that we could work together to make it ready.
